add support for 32&64 bit gstreamer and different linux distribution
linuxdeploy/linuxdeploy-plugin-gstreamer pull request #14
Opened 2022-02-07 23:22 UTC by zerobikappa

Add support for 32&64 bit gstreamer due to the current version only copy 32-bit and 64-bit plugins in the same place.
Add support for different linux distribution due to different library path in different distribution. I did not add option to specify the `$plugins_target_dir`, only keep the same structure between `/` and `$APPDIR`. If necessary to add option to specify the `$plugins_target_dir`, please tell me, thanks.

2022-02-07 23:25 UTC, TheAssassin commented
Please run `shellcheck` on the script and fix the escaping issues.

2022-02-08 07:25 UTC, zerobikappa commented
I'm a new beginner of git. if I did something wrong, I will apologize -- should I leave a comment here so that github will tell you I submitted the changes? or I can just push my changes to my fork then wait for your comment, without leaving a comment here?

2022-02-08 07:52 UTC, TheAssassin commented
Just pushing is enough to trigger a notification. You need to wait for people to have time, though.

2022-02-08 20:40 UTC, zerobikappa commented
well, at last I completed my fork. however, finally I got some doubt whether it is really necessary to add support for other distro. because it seems to be more recommended to package appimage in the oldest still-support ubuntu system.
please let me know you comment.

2022-02-13 23:06 UTC, TheAssassin requested changes

2022-02-13 23:06 UTC, TheAssassin commented on linuxdeploy-plugin-gstreamer.sh
> +    helpers_dir="${GSTREAMER_HELPERS_DIR%"/"}"
Why are you removing the trailing slash(s)? Technically, it should not be needed. Please provide a comment showing your intention.

2022-02-13 23:06 UTC, TheAssassin commented on linuxdeploy-plugin-gstreamer.sh
> +        echo "Error: please consider to specify \$GSTREAMER_HELPERS_DIR"
```suggestion
        echo "Error: please consider specifying \$GSTREAMER_HELPERS_DIR"
```

2022-02-13 23:06 UTC, TheAssassin commented on linuxdeploy-plugin-gstreamer.sh
> +    echo "Error: could not find helpers directory: $helpers_dir"
The `exit` is missing now. I don't think that's on purpose.

2022-02-13 23:06 UTC, TheAssassin commented on linuxdeploy-plugin-gstreamer.sh
> +if [ -n "$helpers_dir" ] && [ ! "$helpers_dir" = "$plugins_dir" ]; then
In bash, you can just use `!=`, which is easier to read and understand.

2022-02-13 23:06 UTC, TheAssassin commented on linuxdeploy-plugin-gstreamer.sh
> +export GST_PLUGIN_SYSTEM_PATH_1_0="\${APPDIR}/${plugins_dir#"/"}"
Yet again, removing the trailing slashes seems unnecessary. Also, you shouldn't repeat yourself over and over again. Just do it once. https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

It's a bit of a pity that escaping is now needed for the `APPDIR` env var, but what you've done looks solid to me.

2022-02-13 23:06 UTC, TheAssassin commented
We're making progress here. I've left a few comments.

2022-02-13 23:07 UTC, TheAssassin commented
> I got some doubt whether it is really necessary to add support for other distro. because it seems to be more recommended to package appimage in the oldest still-support ubuntu system.

Even if it is just a recommendation (I think it is, some people may be more restrictive), old systems must still be supported to allow people to follow this recommendation. If a script just doesn't work on older distros any more, you would force people to use more recent base systems. That does not make sense.

2023-03-16 19:52 UTC, closed without merging